### PR TITLE
Add PCLMock

### PR DESCRIPTION
**Pull request by kentcb**
Adds [PCLMock](https://github.com/kentcb/PCLMock) benchmarks.

Note:

1. I have not updated the README (I figure you'd want to re-run the benchmarks on the same machine anyway)
2. In order to test that benchmarks were running, I had to comment out Rocks stuff because it was failing with a missing assembly problem. Just thought I'd mention this (I've not included the commenting out in my PR, of course)

### CODE REVIEW

**Comment by JasonBock** [comment]
@kentcb I'm curious, what exactly was the error you were getting with Rocks? Was it during compile-time, or runtime?

**Comment by kentcb** [comment]
@JasonBock I get this:
```
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Net.NetworkInformation, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Rocks.Construction.Compiler.<.cctor>g__LoadDependencies2_1(HashSet`1 loadedAssemblies, Assembly fromAssembly)
   at Rocks.Construction.Compiler.<>c.<.cctor>b__2_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Rocks.Construction.Compiler`1.GetReferences()
   at Rocks.Construction.Compiler`1.Compile()
   at Rocks.Construction.InMemory.InMemoryMaker..ctor(Type baseType, ReadOnlyDictionary`2 handlers, SortedSet`1 namespaces, RockOptions options, Boolean isMake)
   at Rocks.InMemoryRock`1.GetMockType(ReadOnlyDictionary`2 readOnlyHandlers)
   at Rocks.InMemoryRock`1.Make()
   at BenchmarkMockNet.Benchmarks.Construction.Rocks() in C:\Users\Kent\Repository\BenchmarkMockNet\Benchmarks\Construction.cs:line 44
   at BenchmarkMockNet.BenchmarkTestHelpers.<>c__DisplayClass2_0`1.<Run>b__5() in C:\Users\Kent\Repository\BenchmarkMockNet\BenchmarkTests.cs:line 49
   at BenchmarkMockNet.BenchmarkTestHelpers.Test(String test, String type, Func`1 pass) in C:\Users\Kent\Repository\BenchmarkMockNet\BenchmarkTests.cs:line 38
   at BenchmarkMockNet.BenchmarkTestHelpers.Run[T](IMockingBenchmark`1 benchmark) in C:\Users\Kent\Repository\BenchmarkMockNet\BenchmarkTests.cs:line 49
   at BenchmarkMockNet.BenchmarkTests.RunAll() in C:\Users\Kent\Repository\BenchmarkMockNet\BenchmarkTests.cs:line 10
   at BenchmarkMockNet.Program.Main(String[] args) in C:\Users\Kent\Repository\BenchmarkMockNet\Program.cs:line 10
```

**Comment by JasonBock** [comment]
Odd. @stevedesmond-ca was able to get it to build and run so....not sure why you have that issue. I know I had some issues getting Rocks to build and run on .NET Core and Benchmark.NET also needed to do a change to ensure some settings in the .csproj file made it into the projects they build when the tests are run. But you shouldn't have seen those.

**Comment by stevedesmond-ca** [comment]
Confirmed that Rocks benchmarks still work on master, but not with this PR -- I believe it's because PCLMock doesn't target netstandard/netcoreapp, and the PCL Profile336 that's being used isn't netstandard-compatible ([link](http://danrigby.com/2014/05/14/supported-pcl-profiles-xamarin-for-visual-studio-2/)) so it's referencing assemblies outside of netstandard, which Rocks is then trying to load.

It looks like you've already got [an open issue for this](https://github.com/kentcb/PCLMock/issues/31), so once that's done, we can revisit this. Or, for a quicker fix, it looks like [this doc](https://docs.microsoft.com/en-us/dotnet/standard/library) about half-way down has a list of netstandard-compatible PCL profiles.

**Comment by stevedesmond-ca** [comment]
Closing for now, as it looks like the work required is still "on hold"

**Pull request closed without merging**
